### ISSUE TITLE
bakery test exhausts open file limit when query logging is enabled

### ISSUE THREAD

**Issue by alexweissman** [userfrosting/UserFrosting#1127]
If I run `bakery test` without query logging, it works fine. But when I run it with `debug.queries = true` set in my config, it quickly exhausts MacOS's default limit on the maximum number of open files:

```
PHPUnit 8.5.11 by Sebastian Bergmann and contributors.

............................................................S..  63 / 591 ( 10%)
............................................................... 126 / 591 ( 21%)
............................................................... 189 / 591 ( 31%)
............................................................... 252 / 591 ( 42%)
............................................................PHP Warning:  include(/Users/alexw/dev/htdocs/UserFrosting/app/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.:/usr/local/Cellar/php/7.4.10/share/php/pear') in /Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(/Users/alexw/dev/htdocs/UserFrosting/app/vendor/phpunit/phpunit/src/Framework/Error/Warning.php): failed to open stream: Too many open files in /Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/ClassLoader.php on line 444
PHP Warning:  include(): Failed opening '/Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/../phpunit/phpunit/src/Framework/Error/Warning.php' for inclusion (include_path='.:/usr/local/Cellar/php/7.4.10/share/php/pear') in /Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/ClassLoader.php on line 444
<strong>Fatal error</strong>: Uncaught Error: Class 'PHPUnit\Framework\Error\Warning' not found in /Users/alexw/dev/htdocs/UserFrosting/app/vendor/phpunit/phpunit/src/Util/ErrorHandler.php:101
Stack trace:
#0 /Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/ClassLoader.php(444): PHPUnit\Util\ErrorHandler->__invoke(2, 'include(/Users/...', '/Users/alexw/de...', 444, Array)
#1 /Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/ClassLoader.php(444): include()
#2 /Users/alexw/dev/htdocs/UserFrosting/app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/Users/alexw/de...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('PHPUnit\\Framewo...')
#4 /Users/alexw/dev/htdocs/UserFrosting/app/vendor/phpunit/phpunit/src/Framework/TestResult.php(738): spl_autoload_call('PHPUnit\\Framewo...')
#5 /Users/alexw/dev/htdocs/UserFrosting/app/vendor/phpunit/phpunit/src/Framework/TestCase.php(763): PHPUnit\Framework\TestResult->run(Object(UserFrosting\Sprinkle\Admin\Tests\Integration\Controller\RoleControllerTe in <strong>/Users/alexw/dev/htdocs/UserFrosting/app/vendor/phpunit/phpunit/src/Util/ErrorHandler.php</strong> on line <strong>101</strong>
```

Not only is it unable to open the log file after a certain point, it's not even able to open the PHP class file that contains the error-handling code for php warnings. Kind of ironic 😂 

Seems like there's something wrong with the way we're interacting with the logger, where it's not properly closing the file after write.

**Comment by Silic0nS0ldier** [comment]
Fairly sure the log files are kept open to enable efficient writes, with the file typically being closed in destructors.

My guess is that loggers are constructed during setup for a lot of tests, resulting in a memory leak. Running tests in separate threads _could_ offer a workaround. Caching logger instances would also offer a workaround, however it seems like an anti-pattern.

**Comment by alexweissman** [comment]
Seems like a question for @lcharette as he has designed most of our testing environment.

**Comment by lcharette** [comment]
Since loggers are created as a service providers, these are reset for each test since we (usually) want each test to run a fresh env. So it's probably part of how tests are run, and part of how the logger operate. 

That being said, running the query log during test is probably not something wise to do. Or at least if you do, running the only specific test suite you need debugging might be better. Or maybe use xdebug to debug the test. We could probably set this up in the testing config env. 

FYI, I can't replicate on Homestead VM. The only thing I managed to replicate is this : 

```
1) UserFrosting\Sprinkle\Core\Tests\Integration\Bakery\LocaleCompareCommandTest::testCommandWithArguments
InvalidArgumentException: Invalid resource log://

/home/vagrant/UserFrosting/app/vendor/userfrosting/uniformresourcelocator/src/ResourceLocator.php:616
/home/vagrant/UserFrosting/app/vendor/userfrosting/uniformresourcelocator/src/ResourceLocator.php:558
/home/vagrant/UserFrosting/app/vendor/userfrosting/uniformresourcelocator/src/ResourceLocator.php:331
/home/vagrant/UserFrosting/app/vendor/userfrosting/uniformresourcelocator/src/ResourceLocator.php:500
/home/vagrant/UserFrosting/app/sprinkles/core/src/ServicesProvider/ServicesProvider.php:519
/home/vagrant/UserFrosting/app/vendor/pimple/pimple/src/Pimple/Container.php:118
/home/vagrant/UserFrosting/app/vendor/slim/slim/Slim/Container.php:109
/home/vagrant/UserFrosting/app/vendor/slim/slim/Slim/Container.php:164
/home/vagrant/UserFrosting/app/sprinkles/core/src/ServicesProvider/ServicesProvider.php:307
/home/vagrant/UserFrosting/app/vendor/pimple/pimple/src/Pimple/Container.php:118
/home/vagrant/UserFrosting/app/vendor/slim/slim/Slim/Container.php:109
/home/vagrant/UserFrosting/app/vendor/slim/slim/Slim/Container.php:164
/home/vagrant/UserFrosting/app/tests/TestCase.php:114
```

**Comment by Silic0nS0ldier** [comment]
Disabling logging in tests sounds like a reasonable workaround for the moment.

Long term (i.e. some future major update to UF) we should think about how we can reduce testing overhead. That we having this issue suggests the bulk of the tests lean more towards integration testing then unit testing.
