### ISSUE TITLE
Uf alert not returning clear error when initialized twice.

### ISSUE THREAD

**Issue by abdullahseba** [userfrosting/UserFrosting#700]
When uf alert is initialized twice in the same page `$("#alerts-page").ufAlerts();` 
it returns:

```
uf-alerts.js:297 Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at n.fn.init.$.fn.(anonymous function) [as ufAlerts] (http://192.168.1.146:83/assets-raw/core/assets/local/core/js/uf-alerts.js:297:35)
    at Object.<anonymous> (http://192.168.1.146:83/assets-raw/webmail/assets/js/email-login.js:22:23)
    at i (http://code.jquery.com/jquery-2.2.4.min.js:2:27151)
    at Object.fireWith [as rejectWith] (http://code.jquery.com/jquery-2.2.4.min.js:2:27914)
    at z (http://code.jquery.com/jquery-2.2.4.min.js:4:12084)
    at XMLHttpRequest.<anonymous> (http://code.jquery.com/jquery-2.2.4.min.js:4:15619)

**Comment by lcharette** [comment]
(Related #646)

**Comment by lcharette** [comment]
Ref.: https://github.com/userfrosting/UserFrosting/blob/master/app/sprinkles/core/assets/local/core/js/uf-alerts.js#L296-L297

In this, the plugin is reinitialized, so there's already an `instance`, but no `methodOrOptions`. Woudn't adding `&& methodOrOptions` between those two lines linked above solve the problem? This would force re-init of the plugin in the next `if` block.

Another solution would be a new to add a new `if (instance && !methodOrOptions)` test to display a `plugin already initialized` warning.

**Comment by Silic0nS0ldier** [comment]
Definitely related to #646.
Should be fixed as of the next hotfix release.

**Comment by alexweissman** [comment]
Can this be closed, now that we've refactored all the plugins?

**Comment by abdullahseba** [comment]
ok
