### ISSUE TITLE
Error while accessing Permissions | Account settings page using Postgres - QueryException 

### ISSUE THREAD

**Issue by Forge-Media** [userfrosting/UserFrosting#780]
Hi, I've just installed UF on my dev environment following the tutorial at [learn.userfrosting.com](http://learn.userfrosting.com), I'm using Postgres as my database driver. 

**My environment versions are:**
- PHP 7.0.22
- PostgreSQL 9.3.17

Once I had finished the installation:
`$ php bakery bake` Which showed no errors

I double checked the app and discovered the following:

URL:  `...userfrosting/public/permissions/p/10#&sort[table-permission-users][name]=asc&page[table-permission-users]=1&size[table-permission-users]=10`

![image](https://user-images.githubusercontent.com/7041755/29153384-3394e3a4-7d85-11e7-86f5-414c6c2ec73b.png)

This is happening on when ever I click on any permission, `Account settings page`, `Activity monitor`, etc.

```
UserFrosting Application Error
The application could not run because of the following error:

Details

Type: PDOException
Code: 42803
Message: SQLSTATE[42803]: Grouping error: 7 ERROR: column "users.id" must appear in the GROUP BY clause or be used in an aggregate function LINE 1: select "users"."id" from "users" inner join "role_users" on ... ^ (SQL: select "users"."id" from "users" inner join "role_users" on "users"."id" = "role_users"."user_id" inner join "permission_roles" on "permission_roles"."role_id" = "role_users"."role_id" where "permission_id" = 1 and "users"."deleted_at" is null group by "user_id" order by "last_name" asc limit 10)
File: …/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php
Line: 105
```

Any chances to get a fix/workaround for this?

**Comment by alexweissman** [comment]
I'm not sure about Postgres, but in MySQL this is usually an issue with your database's configuration of [`ONLY_FULL_GROUP_BY`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by).  However, I thought I had designed the `BelongsToManyThrough` relation to avoid this issue.  I'll look into this, but in the meantime finding Postgres' equivalent to `ONLY_FULL_GROUP_BY` might help you.

**Comment by alexweissman** [comment]
confirmed that this is an issue in mysql as well when `ONLY_FULL_GROUP_BY` is enabled.

**Comment by lcharette** [comment]
I've got this somewhere else before. Defining the select manually should fix this if I remember correctly

**Comment by Forge-Media** [comment]
Hi, thanks for the reply.

Possible that I'm not looking hard enough but I'm not having much success trying to find Postgres's version of `ONLY_FULL_GROUP_BY`. 

I've also seen it referred to as Strict SQL Mode and an older post suggests that postgresql 8.3+ does not have such an option like mysql has. [Source](https://www.postgresql.org/message-id/51C866D3.6000909@commandprompt.com).

Would it be possible for me to simply rerun `$ php bakery bake` and use MySql/mariaDB instead of Postgres or will rerunning bakery bake not work?

**Comment by alexweissman** [comment]
If you want to switch to MySql, you can do so at any time - just rerun Bakery!

**Comment by Forge-Media** [comment]
As I'm really just following the tutorial to get to grips with UF I think that would be my best option.

Thanks

**Comment by alexweissman** [comment]
It's odd, because I thought had addressed this issue back in 4.0!  https://github.com/userfrosting/UserFrosting/commit/33020702be42eccad3e0331e32af1f1d21a38dbc  I'm surprised that it took this long to turn up again.

**Comment by lcharette** [comment]
> If you want to switch to MySql, you can do so at any time - just rerun Bakery!

FYI, rerunning bake won't work on it's own. You must use the `php bakery setup -f` command to re-enter the config. Or just edit the `app/.env` file ;)

**Comment by faligor** [comment]
I have the same error but with MSSQL server when I'm opening some user's page. I do believe that this error shows up only when `BelongsToManyThrough` is involved because all other tables load successfully. 
I'm using UF version `4.1.17-alpha`. See logs below:

```
SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Column &quot;permissions.name&quot; is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.
File: \app\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOStatement.php
Line: 143
Trace: #0 \app\vendor\illuminate\database\Connection.php(323): Doctrine\DBAL\Driver\PDOStatement->execute()
#1 \app\vendor\illuminate\database\Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('select top 10 [...', Array)
#2 \app\vendor\illuminate\database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('select top 10 [...', Array, Object(Closure))
#3 \app\vendor\illuminate\database\Connection.php(326): Illuminate\Database\Connection->run('select top 10 [...', Array, Object(Closure))
#4 \app\vendor\illuminate\database\Query\Builder.php(1705): Illuminate\Database\Connection->select('select top 10 [...', Array, true)
#5 \app\sprinkles\core\src\Database\Builder.php(103): Illuminate\Database\Query\Builder->runSelect()
#6 \app\vendor\illuminate\database\Eloquent\Builder.php(462): UserFrosting\Sprinkle\Core\Database\Builder->get(Array)
#7 \app\vendor\illuminate\database\Eloquent\Builder.php(446): Illuminate\Database\Eloquent\Builder->getModels(Array)
#8 \app\sprinkles\core\src\Database\Relations\Concerns\Unique.php(297): Illuminate\Database\Eloquent\Builder->get()
#9 \app\sprinkles\core\src\Database\Relations\Concerns\Unique.php(333): UserFrosting\Sprinkle\Core\Database\Relations\BelongsToManyThrough->getPaginatedQuery(Object(Illuminate\Database\Eloquent\Builder), '10', 0)
#10 \app\sprinkles\core\src\Database\Relations\Concerns\Unique.php(249): UserFrosting\Sprinkle\Core\Database\Relations\BelongsToManyThrough->getModels(Array, true)
#11 \app\sprinkles\core\src\Sprunje\Sprunje.php(303): UserFrosting\Sprinkle\Core\Database\Relations\BelongsToManyThrough->get()
#12 \app\sprinkles\core\src\Sprunje\Sprunje.php(210): UserFrosting\Sprinkle\Core\Sprunje\Sprunje->getModels()
#13 \app\sprinkles\core\src\Sprunje\Sprunje.php(196): UserFrosting\Sprinkle\Core\Sprunje\Sprunje->getArray()
#14 \app\sprinkles\admin\src\Controller\UserController.php(772): UserFrosting\Sprinkle\Core\Sprunje\Sprunje->toResponse(Object(Slim\Http\Response))
#15 [internal function]: UserFrosting\Sprinkle\Admin\Controller\UserController->getPermissions(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#16 \app\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#17 \app\vendor\slim\slim\Slim\Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#18 \app\sprinkles\account\src\Authenticate\AuthGuard.php(51): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 [internal function]: UserFrosting\Sprinkle\Account\Authenticate\AuthGuard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#20 \app\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Array, Array)
#21 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#22 \app\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#23 \app\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#24 \app\vendor\slim\slim\Slim\Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 \app\vendor\slim\slim\Slim\App.php(513): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 \app\vendor\slim\csrf\src\Guard.php(171): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#28 \app\vendor\slim\slim\Slim\DeferredCallable.php(43): call_user_func_array(Object(Slim\Csrf\Guard), Array)
#29 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#30 \app\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#31 \app\vendor\slim\slim\Slim\MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#32 \app\vendor\slim\slim\Slim\App.php(406): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#33 \app\vendor\slim\slim\Slim\App.php(314): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#34 \app\system\UserFrosting.php(120): Slim\App->run()
#35 \public\index.php(23): UserFrosting\System\UserFrosting->run()
#36 {main}
```

**Comment by faligor** [comment]
I think I have a fix. I think this issue shows up only with MSSQL, so I found a solution: in class `UserFrosting\Sprinkle\Core\Database\Relations\Concerns\Unique` function `getPaginatedQuery`, line 282 add the following:

```
foreach ($subQuery->getQuery()->orders as $order) {
                $subQuery->groupBy($order['column']);
            }
```
now selecting `belongsToManyThrough ` with `withVia ` works properly on my environment. 

but I didn't find a solution how to not override UF's files using my own Sprinkle or class...

**Comment by alexweissman** [comment]
@faligor is this a general-purpose solution? If so, you could consider making a pull request with this fix.
