### ISSUE TITLE
syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by jangrewe** [userfrosting/UserFrosting#862]
So i just did my first live deployment, all seems to be working as expected, except for logging in as the root user and going to the dashboard - which throws this error:
```
[2018-03-24 15:45:17] errors.ERROR: UserFrosting Application Error:
Type: ParseError
Message: syntax error, unexpected '?', expecting variable (T_VARIABLE)
File: /srv/www/betadiff.com/app/vendor/symfony/translation/Translator.php
Line: 79
Trace: #0 /srv/www/betadiff.com/app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/srv/www/betadi...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#2 /srv/www/betadiff.com/app/vendor/nesbot/carbon/src/Carbon/Translator.php(7): spl_autoload_call('Symfony\\Compone...')
#3 /srv/www/betadiff.com/app/vendor/composer/ClassLoader.php(444): include('/srv/www/betadi...')
#4 /srv/www/betadiff.com/app/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/srv/www/betadi...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('Carbon\\Translat...')
#6 /srv/www/betadiff.com/app/vendor/nesbot/carbon/src/Carbon/Carbon.php(1389): spl_autoload_call('Carbon\\Translat...')
#7 /srv/www/betadiff.com/app/vendor/nesbot/carbon/src/Carbon/Carbon.php(3504): Carbon\Carbon::translator()
#8 /srv/www/betadiff.com/app/sprinkles/admin/src/Controller/AdminController.php(56): Carbon\Carbon->diffForHumans()
#9 [internal function]: UserFrosting\Sprinkle\Admin\Controller\AdminController->UserFrosting\Sprinkle\Admin\Controller\{closure}(Object(UserFrosting\Sprinkle\UserProfile\Database\Models\User), 0)
#10 /srv/www/betadiff.com/app/vendor/illuminate/support/Collection.php(766): array_map(Object(Closure), Array, Array)
#11 /srv/www/betadiff.com/app/vendor/illuminate/database/Eloquent/Collection.php(134): Illuminate\Support\Collection->map(Object(Closure))
#12 /srv/www/betadiff.com/app/vendor/illuminate/support/Collection.php(1369): Illuminate\Database\Eloquent\Collection->map(Object(Closure))
#13 /srv/www/betadiff.com/app/sprinkles/admin/src/Controller/AdminController.php(58): Illuminate\Support\Collection->transform(Object(Closure))
#14 [internal function]: UserFrosting\Sprinkle\Admin\Controller\AdminController->pageDashboard(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#15 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#16 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/Route.php(335): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#17 /srv/www/betadiff.com/app/sprinkles/account/src/Authenticate/AuthGuard.php(51): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 [internal function]: UserFrosting\Sprinkle\Account\Authenticate\AuthGuard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#19 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Array, Array)
#20 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#21 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#22 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#23 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/Route.php(313): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#24 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/App.php(495): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 /srv/www/betadiff.com/app/vendor/slim/csrf/src/Guard.php(171): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 [internal function]: Slim\Csrf\Guard->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#27 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array(Object(Slim\Csrf\Guard), Array)
#28 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#29 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#30 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#31 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/App.php(388): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#32 /srv/www/betadiff.com/app/vendor/slim/slim/Slim/App.php(296): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#33 /srv/www/betadiff.com/app/system/UserFrosting.php(120): Slim\App->run()
#34 /srv/www/betadiff.com/public/index.php(23): UserFrosting\System\UserFrosting->run()
#35 {main}
View in rendered output by enabling the "displayErrorDetails" setting.
 [] []
```
I'm a bit surprised because the whole project works fine in `dev` mode, and even removing `locale/en_US/messages.php` for my custom sprinkle doesn't change anything (except for missing strings, of course).

**Comment by jangrewe** [comment]
moved to https://chat.userfrosting.com/channel/support

**Comment by jangrewe** [comment]
Caused by too new version of dependencies installed, because i was using composer with PHP 7.1 in the CI pipeline, but PHP 7.0 on the server.
